const $ = (s, el=document) => el.querySelector(s);
const money = n => new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(n);
const money2 = n => new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(n);
const SHOP = 'https://life-maker-cash-now.vercel.app';

const APPS = [
  {id:'inkledger',name:'InkLedger',color:'#5eead4',tag:'SaaS',pitch:'Invoices that get paid — beautiful freelancing cashflow.',price:99},
  {id:'clipforge',name:'ClipForge',color:'#a78bfa',tag:'Creator',pitch:'Short-form hooks that stop the scroll.',price:49},
  {id:'nestyield',name:'NestYield',color:'#fbbf24',tag:'Commerce',pitch:'Digital storefront for calm product packs.',price:79},
  {id:'linkgrove',name:'LinkGrove',color:'#34d399',tag:'Links',pitch:'Bio link page that actually sells.',price:29},
  {id:'formafit',name:'FormaFit',color:'#fb7185',tag:'Forms',pitch:'Lead forms with soft conversion copy.',price:39},
  {id:'pulseseo',name:'PulseSEO',color:'#60a5fa',tag:'SEO',pitch:'Keyword gaps → content that compounds.',price:59},
  {id:'coursenest',name:'CourseNest',color:'#c084fc',tag:'Course',pitch:'Ship mini-courses without chaos.',price:89},
  {id:'printmint',name:'PrintMint',color:'#f472b6',tag:'Merch',pitch:'Print-on-demand designs that feel human.',price:35},
  {id:'resumelift',name:'ResumeLift',color:'#2dd4bf',tag:'Career',pitch:'ATS-safe resumes people actually open.',price:19},
  {id:'rentradar',name:'RentRadar',color:'#f59e0b',tag:'Property',pitch:'Yield calculator for acreage & rentals.',price:45},
];

const PRODUCTS = [
  {id:'life-maker-starter-bundle',name:'Life Maker Starter Bundle',price:79,was:117,hot:1,desc:'Therapy starter + calm landing + founder OS. Best first sale.'},
  {id:'sausage-therapy-starter',name:'Sausage Therapy Starter',price:39,desc:'Session structure, welcome notes, soft marketing.'},
  {id:'calm-landing-kit',name:'Calm Landing Kit',price:29,desc:'Honest landing copy for wellness offers.'},
  {id:'founder-notion-os',name:'Founder Notion OS',price:49,desc:'Offers, clients, weekly cash operating system.'},
  {id:'resumelift-ats',name:'ResumeLift ATS Guide',price:19,desc:'ATS-safe resume + cover skeleton.'},
  {id:'clipforge-hooks',name:'ClipForge Hook Pack',price:49,desc:'Reels/Shorts hooks that convert.'},
  {id:'inkledger-pro',name:'InkLedger Pro pack',price:99,desc:'Invoice workflow + reminder scripts.'},
];

const TABS = [
  {id:'home',label:'Home'},{id:'apps',label:'10 Apps'},{id:'shop',label:'Shop'},
  {id:'daily',label:'Daily'},{id:'profit',label:'Profit'},{id:'pay',label:'PayID'},
];

const state = load();
function load(){try{return Object.assign(defaults(), JSON.parse(localStorage.getItem('lm-hub-v2')||localStorage.getItem('lm-hub-v1')||'{}'));}catch(e){return defaults();}}
function defaults(){return{payId:'',payName:'Emily Blue Richards',bsb:'',acc:'',accName:'Emily Blue Richards',email:'emilybluerichards@gmail.com',phone:'0499938590',stripe:'',sales:[],outreach:0,tasks:[{id:'t1',t:'Send 10 warm pitches',done:false,m:25},{id:'t2',t:'Fill PayID rails',done:false,m:2},{id:'t3',t:'Share shop on social',done:false,m:5},{id:'t4',t:'Deliver paid packs same day',done:false,m:10},{id:'t5',t:'Boost the bundle offer',done:false,m:5}],appBoost:Object.fromEntries(APPS.map(a=>[a.id,0])),simMrr:1240};}
function save(){localStorage.setItem('lm-hub-v2', JSON.stringify(state));}
function route(){return (location.hash.replace('#','')||'home').split('/')[0];}
function go(id){location.hash = '#'+id;}
function paidTotal(){return state.sales.filter(s=>s.status==='paid').reduce((a,s)=>a+s.amount,0);}
function esc(s){return String(s||'').replace(/&/g,'&').replace(/"/g,'"').replace(/</g,'<');}
function paintTabs(){const r=route();$('#tabs').innerHTML=TABS.map(t=>`<button class="tab ${t.id===r?'on':''}" data-tab="${t.id}">${t.label}</button>`).join('');$('#tabs').querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>go(b.dataset.tab));}
function pitch(){const pay=state.payId?` PayID ${state.payId}.`:'';return `Hey — calm digital pack (Sausage Therapy Starter). $39 AUD same-day file.${pay} Shop: ${SHOP}`;}
function viewHome(){const paid=paidTotal(),done=state.tasks.filter(t=>t.done).length;return `<div class="hero"><div class="stack"><div class="row"><span class="badge ok">Live · AU</span><span class="badge hot">10 apps deployed</span></div><h1>Build calm products.<br/>Collect real cash.</h1><p class="m" style="margin:0;max-width:34rem">Life Maker is your endless money pool — ten micro-apps, a PayID shop, and a daily engine that keeps you shipping sales.</p><div class="steps"><div class="step"><b>1. Rails</b>Save PayID once</div><div class="step"><b>2. Pitch</b>Ten warm messages</div><div class="step"><b>3. Deliver</b>File same day · bank fills</div></div><div class="row"><button class="btn ba" onclick="go('shop')">Open shop</button><button class="btn" onclick="go('daily')">Daily engine</button><a class="btn bg" href="${SHOP}" target="_blank" rel="noreferrer">Cash storefront</a></div></div><div class="card feat stack"><span class="badge hot">Best first sale</span><h2>Starter Bundle</h2><p class="m" style="margin:0">Therapy starter + landing kit + founder OS</p><div><span class="strike">$117</span><span class="price">${money2(79)}</span></div><button class="btn ba" data-order="life-maker-starter-bundle" type="button">Order bundle</button><div class="s">PayID · bank · optional Stripe · same-day delivery</div></div></div><div class="grid g4" style="margin-bottom:1rem"><div class="card stat"><div class="s">Real sales</div><div class="price">${money2(paid)}</div></div><div class="card stat"><div class="s">Outreach</div><div class="price">${state.outreach}/10</div></div><div class="card stat"><div class="s">Model MRR</div><div class="price">${money(state.simMrr)}</div></div><div class="card stat"><div class="s">Daily tasks</div><div class="price">${done}/${state.tasks.length}</div></div></div><div class="card stack"><div class="row" style="justify-content:space-between"><strong style="font-family:var(--display)">Cash pitch</strong><span class="badge">Copy · SMS · WhatsApp</span></div><div class="pitch">${esc(pitch())}</div><div class="row"><button class="btn ba" id="copyPitch">Copy pitch</button><button class="btn" id="sentOne">I sent one</button><button class="btn bg" onclick="go('pay')">Set PayID</button></div></div>`;}
function viewApps(){return `<div class="stack" style="padding-top:.6rem"><h1>10 Masterpieces</h1><p class="m" style="margin:0">Each app is a product surface you can sell today. Boost increases modeled portfolio weight.</p><div class="grid g2">${APPS.map(a=>`<div class="card stack"><div class="row"><span class="dot" style="background:${a.color};color:${a.color}"></span><strong style="font-family:var(--display)">${a.name}</strong><span class="badge">${a.tag}</span></div><div class="m">${a.pitch}</div><div class="row" style="justify-content:space-between"><span class="price">${money2(a.price)}</span><span class="s">Boost ${state.appBoost[a.id]||0}</span></div><div class="row"><button class="btn ba" data-sell="${a.id}">Sell pack</button><button class="btn" data-boost="${a.id}">Boost +</button></div></div>`).join('')}</div></div>`;}
function viewShop(){return `<div class="stack" style="padding-top:.6rem"><h1>Passive Shop</h1><p class="m" style="margin:0">Order → pay → mark paid → deliver. No fake balances.</p><div class="grid g2">${PRODUCTS.map(p=>`<div class="card stack ${p.hot?'feat':''}">${p.hot?'<span class="badge hot">Best value</span>':''}<strong style="font-family:var(--display)">${p.name}</strong><div class="m">${p.desc}</div><div>${p.was?`<span class="strike">${money2(p.was)}</span>`:''}<span class="price">${money2(p.price)}</span></div><div class="row"><button class="btn ba" data-order="${p.id}">Order / PayID</button><button class="btn" data-mark="${p.id}">Mark paid</button></div></div>`).join('')}</div></div>`;}
function viewDaily(){const done=state.tasks.filter(t=>t.done).length,pct=Math.round(done/state.tasks.length*100);return `<div class="stack" style="padding-top:.6rem"><h1>Daily engine</h1><p class="m" style="margin:0">One board. Cash first. Tick tasks and the week compounds.</p><div class="card stack"><div class="row" style="justify-content:space-between"><span>${done}/${state.tasks.length} complete</span><span class="mono">${pct}%</span></div><div class="bar"><i style="width:${pct}%"></i></div></div><div class="stack">${state.tasks.map(t=>`<button class="btn" style="justify-content:flex-start;text-align:left;opacity:${t.done?.7:1}" data-task="${t.id}">${t.done?'✓':'○'}&nbsp;&nbsp;${t.t} · <span class="s">${t.m}m</span></button>`).join('')}</div><div class="row"><button class="btn ba" id="profitPush">One-tap profit push</button><button class="btn bg" id="resetTasks">Reset day</button></div></div>`;}
function viewProfit(){const paid=paidTotal(),pending=state.sales.filter(s=>s.status==='pending');return `<div class="stack" style="padding-top:.6rem"><h1>Profit & withdraw</h1><div class="grid g2"><div class="card feat"><div class="s">Available ledger</div><div class="price">${money2(paid)}</div><div class="s">PayID/bank = cash already in your account</div></div><div class="card"><div class="s">Pending orders</div><div class="price">${pending.length}</div><div class="s">Waiting for buyer payment</div></div></div><div class="card stack"><strong style="font-family:var(--display)">Sales ledger</strong>${state.sales.length?state.sales.slice(0,24).map(s=>`<div class="row" style="justify-content:space-between;border-top:1px solid var(--b);padding:.5rem 0"><span>${esc(s.name)} · <span class="s">${s.status}</span></span><span class="mono">${money2(s.amount)}</span></div>`).join(''):'<div class="s">No sales yet — open Shop and take a PayID order.</div>'}</div><button class="btn ba" onclick="go('shop')">Take an order</button></div>`;}
function viewPay(){return `<div class="stack" style="padding-top:.6rem"><h1>Money rails</h1><p class="m" style="margin:0">Saved on this device. Required so pay instructions copy cleanly.</p><div class="card stack"><label>PayID</label><input id="payId" value="${esc(state.payId)}" placeholder="email or 04… mobile"/><label>PayID name</label><input id="payName" value="${esc(state.payName)}"/><label>BSB</label><input id="bsb" value="${esc(state.bsb)}" placeholder="000-000"/><label>Account number</label><input id="acc" value="${esc(state.acc)}"/><label>Account name</label><input id="accName" value="${esc(state.accName)}"/><label>Seller email</label><input id="email" value="${esc(state.email)}"/><label>Phone</label><input id="phone" value="${esc(state.phone)}"/><label>Stripe Payment Link (optional)</label><input id="stripe" value="${esc(state.stripe)}" placeholder="https://buy.stripe.com/…"/><button class="btn ba" id="savePay">Save rails</button></div></div>`;}
function render(){paintTabs();const r=route(),map={home:viewHome,apps:viewApps,shop:viewShop,daily:viewDaily,profit:viewProfit,pay:viewPay};$('#app').innerHTML=(map[r]||viewHome)();bind();window.scrollTo({top:0,behavior:'instant'});}
function bind(){const cp=$('#copyPitch');if(cp)cp.onclick=async()=>{try{await navigator.clipboard.writeText(pitch());alert('Pitch copied — paste into 10 chats');}catch(e){alert(pitch());}};const so=$('#sentOne');if(so)so.onclick=()=>{state.outreach=Math.min(10,state.outreach+1);save();render();};document.querySelectorAll('[data-boost]').forEach(b=>b.onclick=()=>{const id=b.dataset.boost;state.appBoost[id]=(state.appBoost[id]||0)+1;state.simMrr=Math.round(state.simMrr*1.03);save();render();});document.querySelectorAll('[data-sell]').forEach(b=>b.onclick=()=>go('shop'));document.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>{const p=PRODUCTS.find(x=>x.id===b.dataset.order);if(!p)return;const ref='LM-'+Date.now().toString(36).toUpperCase();state.sales.unshift({id:ref,name:p.name,amount:p.price,status:'pending',at:Date.now()});save();const lines=[`Pay ${money2(p.price)} for ${p.name}`,`Ref ${ref}`];if(state.payId)lines.push(`PayID: ${state.payId} (${state.payName})`);if(state.bsb&&state.acc)lines.push(`BSB ${state.bsb} Acc ${state.acc} ${state.accName}`);lines.push(SHOP);const text=lines.join('\n');const subject=encodeURIComponent(`Order ${ref} — ${p.name}`);const body=encodeURIComponent(text);location.href=`mailto:${state.email||'emilybluerichards@gmail.com'}?subject=${subject}&body=${body}`;});document.querySelectorAll('[data-mark]').forEach(b=>b.onclick=()=>{const p=PRODUCTS.find(x=>x.id===b.dataset.mark);if(!p)return;const pending=state.sales.find(s=>s.name===p.name&&s.status==='pending');if(pending)pending.status='paid';else state.sales.unshift({id:'LM-'+Date.now().toString(36),name:p.name,amount:p.price,status:'paid',at:Date.now()});save();render();});document.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>{const t=state.tasks.find(x=>x.id===b.dataset.task);if(t)t.done=!t.done;save();render();});const pp=$('#profitPush');if(pp)pp.onclick=()=>{state.tasks.forEach(t=>t.done=true);state.simMrr=Math.round(state.simMrr*1.08);save();render();};const rt=$('#resetTasks');if(rt)rt.onclick=()=>{state.tasks.forEach(t=>t.done=false);save();render();};const sp=$('#savePay');if(sp)sp.onclick=()=>{['payId','payName','bsb','acc','accName','email','phone','stripe'].forEach(k=>{const el=$('#'+k);if(el)state[k]=el.value.trim();});save();alert('Rails saved on this device');render();};}
$('#goShop').onclick=()=>go('shop');
$('#goDaily').onclick=()=>go('daily');
const ga=$('#goApps');if(ga)ga.onclick=()=>go('apps');
window.addEventListener('hashchange', render);
render();
